esewa/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('myapp.urls')),
]

myapp/urls.py
from django.urls import path
from .views import *


app_name = 'myapp'

urlpatterns = [
    path('',home, name="home"),
    # path('esewa-payment/',AsyncView.as_view()),
    # path('verify-esewa-payment/',esewaPaymentVerification, name="verify-esewa-payment"),
    path('khalti-payment/',khaltipayment, name="khalti-payment"),
    path('verify-khalti-payment/',khaltiPaymentVerification, name="verify-khalti-payment"),
]

myapp/models.py
# from django.db import models


# class User(models.Model):
#     username = models.CharField(max_length=25,unique=True)


# class Product(models.Model):
#     name = models.CharField(max_length=100)
#     amount = models.DecimalField(decimal_places=2,max_digits=5)

# class PurchaseOrder(models.Model):
#     user = models.ForeignKey(User,on_delete=models.CASCADE)
#     Product = models.ForeignKey(Product,on_delete=models.CASCADE)
#     quantity = models.PositiveIntegerField()


# user1 = User.objects.create(username='user 1')
# user2 = User.objects.create(username='user 2')
# user3 = User.objects.create(username='user 3')

# product_a = Product.objects.create(name='product a', amount=100)
# product_b = Product.objects.create(name='product b', amount=120)
# product_c = Product.objects.create(name='product c', amount=150)

# PurchaseOrder.objects.create(user=user1,product=product_a,quantity=3)
# PurchaseOrder.objects.create(user=user2,product=product_b,quantity=5)
# PurchaseOrder.objects.create(user=user3,product=product_c,quantity=5)

myapp/views.py
import json
import requests
from django.views import View
from django.shortcuts import render, HttpResponse, redirect

import hmac
import uuid
import base64
import hashlib


def gen_hmacsha256(key, signature_data):
    hmac_sha256 = hmac.new(key.encode(
        'utf-8'), signature_data.encode('utf-8'), hashlib.sha256)
    signature = base64.b64encode(hmac_sha256.digest()).decode('utf-8')
    return signature

# def gen_hmacshan256(ky, data):
#     hmac_shan256 = hmac.new(ky.encode('utf-8'), data.encode('utf-8'), hashlib.sha256)
#     signature = base64.b64encode(hmac_shan256.digest()).decode('utf-8')
#     return signature


# def home(request):
#     total_amount = 110
#     secret_key = '8gBm/:&EnhH.1/q'
#     transaction_uuid = uuid.uuid4()
#     signature_data = (
#         f"total_amount={total_amount},"
#         f"transaction_uuid={transaction_uuid},"
#         f"product_code=EPAYTEST"
#     )

#     signature = gen_hmacsha256(secret_key, signature_data)

#     context = {
#         'amount':100,
#         'tax_amount':10,
#         'total_amount':110,
#         'signature': signature,
#         'product_code':'EPAYTEST',
#         'transaction_uuid': transaction_uuid,
#     }

#     return render(request, 'home.html', context)



# def esewaPaymentVerification(request):
#     data = request.GET.get('data')
#     decoded_data = base64.b64decode(data).decode('utf-8')
#     map_data = json.loads(decoded_data)
#     if map_data.get('status') == 'COMPLETE':
#         print('eSewa payment completed')
#     return redirect('/')


def home(request):
    uid = uuid.uuid4()
    context = {
        'uid':uid,
        'return_url':'http://127.0.0.1:8000/verify-khalti-payment'
    }

    return render(request, 'home.html', context)

def khaltipayment(request):
    return_url = request.POST.get('return_url')
    amount = request.POST.get('amount')
    purchase_order_id = request.POST.get('purchase_order_id')

    url = "https://a.khalti.com/api/v2/epayment/initiate/"

    payload = json.dumps({
        "return_url": return_url,
        "website_url": "https://127.0.0.1:8000",
        "amount": amount,
        "purchase_order_id": purchase_order_id,
        "purchase_order_name": "test",
        "customer_info": {
        "name": "Ram Bahadur",
        "email": "test@khalti.com",
        "phone": "9800000001"
        }
    })
    headers = {
        'Authorization': 'key c1bf38dde5fb4426b7f9e361e472655d',
        'Content-Type': 'application/json',
    }

    response = requests.request("POST", url, headers=headers, data=payload)
    response = json.loads(response.text)

    return redirect(response['payment_url'])



def khaltiPaymentVerification(request):
    url = "https://a.khalti.com/api/v2/epayment/lookup/"
    headers = {
        'Authorization': 'key c1bf38dde5fb4426b7f9e361e472655d',
        'Content-Type': 'application/json',
    }
    pidx = request.GET.get('pidx')

    payload = json.dumps({
        'pidx':pidx
    })

    response = requests.request("POST", url, headers=headers, data=payload)
    response = json.loads(response.text)

    if response['status'] == 'Completed':
        return redirect('/')






# def generate_hmac_signature(payload, secret_key):
#     # Sort the payload parameters alphabetically
#     sorted_params = sorted(payload.items())
#     print('******************')
#     print(sorted_params)
#     print('******************')

#     # Concatenate the sorted parameter values
#     concatenated_values = ''.join(str(value) for param, value in sorted_params)

#     # Generate the HMAC using SHA-256 and the secret key
#     hashed = hmac.new(secret_key.encode('utf-8'),
#                       concatenated_values.encode('utf-8'), hashlib.sha256)

#     # Encode the result in base64
#     signature = base64.b64encode(hashed.digest()).decode('utf-8')

#     return signature





# def home(request):
#     uuids = uuid.uuid4()
#     total_amount="110"
#     secret_key = '8gBm/:&EnhH.1/q'
#     payload = f"{total_amount},{uuids},EPAYTEST"
#     print(payload)

#     # Add the generated signature to the payload
#     payload = gen_hmacsha256(secret_key,payload)
#     print(payload)

#     return render(request, 'home.html', {'transaction_uuid':uuids,'signature':payload})



# def gen_hmacsha256(key,message):
#     key = key.encode('utf-8')
#     message = message.encode('utf-8')

#     hmac_sha256 = hmac.new(key, message, hashlib.sha256)
#     digest = hmac_sha256.digest()
#     signature = base64.b64encode(digest).decode('utf-8')
#     return signature




# class AsyncView(View):
#     def get(self, request):
#         url = "https://uat.esewa.com.np/epay/transrec"
#         parameters = {
#             'amt': request.GET.get('amt'),
#             'scd': 'EPAYTEST',
#             'rid': request.GET.get('refid'),
#             'pid': request.GET.get('oid'),
#         }
#         resp = req.get(url, parameters)
#         print(resp.text)
#         return HttpResponse(f'status_code---{resp.status_code}------{resp.text}')

templates/home.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/crypto-js/3.1.9-1/crypto-js.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/crypto-js/3.1.9-1/hmac-sha256.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/crypto-js/3.1.9-1/enc-base64.js"></script>

    <title>Document</title>
</head>

<body>

    <form action="https://rc-epay.esewa.com.np/api/epay/main/v2/form" method="POST">
        <input type="text" id="amount" name="amount" value="{{amount}}" required hidden>
        <input type="text" id="tax_amount" name="tax_amount" value="{{tax_amount}}" required hidden>
        <input type="text" id="total_amount" name="total_amount" value="{{total_amount}}" required hidden>
        <input type="text" id="transaction_uuid" name="transaction_uuid" value="{{transaction_uuid}}" hidden>
        <input type="text" id="product_code" name="product_code" value="{{product_code}}" required hidden>
        <input type="text" id="product_service_charge" name="product_service_charge" value="0" required hidden>
        <input type="text" id="product_delivery_charge" name="product_delivery_charge" value="0" required hidden>
        <input type="text" id="success_url" name="success_url" value="http://127.0.0.1:8000/success" required hidden>
        <input type="text" id="failure_url" name="failure_url" value="https://google.com" required hidden>
        <input type="text" id="signed_field_names" name="signed_field_names"
            value="total_amount,transaction_uuid,product_code" required hidden>
        <input type="text" id="signature" name="signature" required value="{{signature}}" hidden>
        <input value="pay with esewa" type="submit">
    </form>
<hr>
    <form action="{% url 'myapp:khalti-payment' %}" method="POST">
        {% csrf_token %}
        <input type="text" id="" name="purchase_order_id" value="{{uid}}" required hidden>
        <input type="text" id="" name="amount" value="1000" required hidden>
        <input type="text" id="" name="return_url" value="{{return_url}}" required hidden>
        <input value="pay with khalti" type="submit">
    </form>


    <!-- <script>
        // Get form values
        var totalAmount = document.getElementById("total_amount").value;
        var transactionUuid = document.getElementById("transaction_uuid").value;
        var productCode = document.getElementById("product_code").value;
    
        // Concatenate the values
        var message = totalAmount + "," + transactionUuid + "," + productCode;
        // document.write(message)
    
        // Get the secret key
        var secretKey = "8gBm/:&EnhH.1/q";
    
        // Generate the HMAC-SHA256 signature
        var hash = CryptoJS.HmacSHA256(message, secretKey);
        var hashInBase64 = CryptoJS.enc.Base64.stringify(hash);
        document.write(hashInBase64)
    
        // Set the signature value in the form
        // document.getElementById("signature").value = hashInBase64;
    </script> -->




</body>

</html>